---
#
# Examples of network device group get-all, get-by-id, get-by-name, create, update, delete.
#
- name: Examples of cisco.ise.network_device[_info]
  hosts: ise_deployment
  vars_files:
    - credentials.yaml
  gather_facts: no
  tasks:


#------------------------------------------------------------------------------
# Example use of the cisco.ise.network_device_info module
# https://ciscoise.github.io/ansible-ise/main/html/plugins/network_device_info_module.html
#------------------------------------------------------------------------------

# - name: Get all Network Device
#   cisco.ise.network_device_info:
#     ise_hostname: "{{ise_hostname}}"
#     ise_username: "{{ise_username}}"
#     ise_password: "{{ise_password}}"
#     ise_verify: "{{ise_verify}}"
#   register: result

# - name: Get Network Device by id
#   cisco.ise.network_device_info:
#     ise_hostname: "{{ise_hostname}}"
#     ise_username: "{{ise_username}}"
#     ise_password: "{{ise_password}}"
#     ise_verify: "{{ise_verify}}"
#     id: string
#   register: result

# - name: Get Network Device by name
#   cisco.ise.network_device_info:
#     ise_hostname: "{{ise_hostname}}"
#     ise_username: "{{ise_username}}"
#     ise_password: "{{ise_password}}"
#     ise_verify: "{{ise_verify}}"
#     name: string
#   register: result


#------------------------------------------------------------------------------
# Example use of the cisco.ise.network_device module:
# https://ciscoise.github.io/ansible-ise/main/html/plugins/network_device_module.html
#------------------------------------------------------------------------------

#   - name: Create
#   cisco.ise.network_device:
#     ise_hostname: "{{ise_hostname}}"
#     ise_username: "{{ise_username}}"
#     ise_password: "{{ise_password}}"
#     ise_verify: "{{ise_verify}}"
#     state: present
#     NetworkDeviceGroupList:
#     - Location#All Locations
#     - IPSEC#Is IPSEC Device#No
#     - Device Type#All Device Types
#     NetworkDeviceIPList:
#     - ipaddress: 1.2.3.4
#       mask: 32
#     authenticationSettings:
#       networkProtocol: RADIUS
#       radiusSharedSecret: C1sco12345
#     description: ''
#     name: nad
#     tacacsSettings:
#       connectModeOptions: false
#       sharedSecret: C1sco12345

# - name: Update by id
#   cisco.ise.network_device:
#     ise_hostname: "{{ise_hostname}}"
#     ise_username: "{{ise_username}}"
#     ise_password: "{{ise_password}}"
#     ise_verify: "{{ise_verify}}"
#     state: present
#     NetworkDeviceGroupList:
#     - Location#All Locations
#     - IPSEC#Is IPSEC Device#No
#     - Device Type#All Device Types
#     NetworkDeviceIPList:
#     - ipaddress: 1.2.3.4
#       mask: 32
#     authenticationSettings:
#       networkProtocol: RADIUS
#       radiusSharedSecret: C1sco12345
#     description: ''
#     id: string
#     name: nad
#     tacacsSettings:
#       connectModeOptions: false
#       sharedSecret: C1sco12345

# - name: Delete by id
#   cisco.ise.network_device:
#     ise_hostname: "{{ise_hostname}}"
#     ise_username: "{{ise_username}}"
#     ise_password: "{{ise_password}}"
#     ise_verify: "{{ise_verify}}"
#     state: absent
#     id: string

# - name: Update by name
#   cisco.ise.network_device:
#     ise_hostname: "{{ise_hostname}}"
#     ise_username: "{{ise_username}}"
#     ise_password: "{{ise_password}}"
#     ise_verify: "{{ise_verify}}"
#     state: present
#     NetworkDeviceGroupList:
#     - Location#All Locations
#     - IPSEC#Is IPSEC Device#No
#     - Device Type#All Device Types
#     NetworkDeviceIPList:
#     - ipaddress: 1.2.3.4
#       mask: 32
#     authenticationSettings:
#       networkProtocol: RADIUS
#       radiusSharedSecret: C1sco12345
#     description: ''
#     name: nad
#     tacacsSettings:
#       connectModeOptions: false
#       sharedSecret: C1sco12345

# - name: Delete by name
#   cisco.ise.network_device:
#     ise_hostname: "{{ise_hostname}}"
#     ise_username: "{{ise_username}}"
#     ise_password: "{{ise_password}}"
#     ise_verify: "{{ise_verify}}"
#     state: absent
#     name: string

...
