---
#
# Examples of network device group get-all, get-by-id, get-by-name, create, update, delete.
#
- name: Examples for cisco.ise.network_device_group[_info]
  hosts: ise_deployment
  vars_files:
    - credentials.yaml
  gather_facts: no
  tasks:


#------------------------------------------------------------------------------
# Example use of the cisco.ise.network_device_group_info module
# https://ciscoise.github.io/ansible-ise/main/html/plugins/network_device_group_info_module.html
#------------------------------------------------------------------------------

  - name: Get all Network Device Group
    cisco.ise.network_device_group_info:
      ise_hostname: "{{ inventory_hostname }}"
      ise_username: "{{ ise_username }}"
      ise_password: "{{ ise_password }}"
      ise_verify: "{{ ise_verify }}"
    register: result


  - name: Debug result
    ansible.builtin.debug:
      var: result


  # - name: Get Network Device Group by id
  #   cisco.ise.network_device_group_info:
  #     ise_hostname: "{{ ise_hostname }}"
  #     ise_username: "{{ ise_username }}"
  #     ise_password: "{{ ise_password }}"
  #     ise_verify: "{{ ise_verify }}"
  #     id: e21fbaa0-ddc8-11eb-8c48-bad9a6479d91
  #   register: result

  # - name: Get Network Device Group by name
  #   cisco.ise.network_device_group_info:
  #     ise_hostname: "{{ ise_hostname }}"
  #     ise_username: "{{ ise_username }}"
  #     ise_password: "{{ ise_password }}"
  #     ise_verify: "{{ ise_verify }}"
  #     name: Device Type#All Device Types#Wireless
  #   register: result


#------------------------------------------------------------------------------
# Example use of the cisco.ise.network_device_group module:
# https://ciscoise.github.io/ansible-ise/main/html/plugins/network_device_group_module.html
#------------------------------------------------------------------------------

  # - name: Create
  #   cisco.ise.network_device_group:
  #     ise_hostname: "{{ inventory_hostname }}"
  #     ise_username: "{{ ise_username }}"
  #     ise_password: "{{ ise_password }}"
  #     ise_verify: "{{ ise_verify }}"
  #     state: present
  #     description: 'Wireless'
  #     name: Device Type#All Device Types#Wireless
  #     othername: Device Type

  # - name: Update by id
  #   cisco.ise.network_device_group:
  #     ise_hostname: "{{ ise_hostname }}"
  #     ise_username: "{{ ise_username }}"
  #     ise_password: "{{ ise_password }}"
  #     ise_verify: "{{ ise_verify }}"
  #     state: present
  #     description: New Wireless Description
  #     id: e21fbaa0-ddc8-11eb-8c48-bad9a6479d91
  #     name: Device Type#All Device Types#Wireless
  #     othername: Device Type

  # - name: Delete by id
  #   cisco.ise.network_device_group:
  #     ise_hostname: "{{ ise_hostname }}"
  #     ise_username: "{{ ise_username }}"
  #     ise_password: "{{ ise_password }}"
  #     ise_verify: "{{ ise_verify }}"
  #     state: absent
  #     id: e21fbaa0-ddc8-11eb-8c48-bad9a6479d91


...
