---
#
# Create network device groups
#

- hosts: ise_deployment
  vars_files:   # assumes same directory as playbook
    - credentials.yaml
    - networkdevicegroups_by_device_type-short.yaml
    # - networkdevicegroups_by_device_type.yaml
    # - networkdevicegroups_by_department.yaml
    # - networkdevicegroups_by_location.yaml
    # - networkdevicegroups_by_medical_department.yaml
    # - networkdevicegroups_by_operations.yaml
    # - networkdevicegroups_by_university_department.yaml
  gather_facts: no
  tasks:


  # This will include all files from a directory; last one wins
  # 
  # For roles, directory location is relative to the role's vars/ subdirectory
  # Otherwise, the directory is relative to the playbook
  #
  # - name: Include networkdevicegroups
  #   ansible.builtin.include_vars:
  #     dir: vars
  #     extensions: ['yaml']
  #     ignore_unknown_extensions: True


  # - name: "Debug: networkdevicegroups"
  #   ansible.builtin.debug: 
  #     var : networkdevicegroups


  - name: List Network Device Groups (YAML)
    ansible.builtin.shell: "echo '{{ networkdevicegroups
    | community.general.json_query(query) 
    | to_nice_yaml(indent=2) }}' > /dev/tty"
    delegate_to: localhost
    changed_when: false
    vars:
      query: "[*].name"


  - name: Create NetworkDeviceGroups 
    cisco.ise.network_device_group:
      ise_hostname: "{{ inventory_hostname }}"
      ise_username: "{{ ise_username }}"
      ise_password: "{{ ise_password }}"
      ise_verify: "{{ ise_verify }}"
      state: present
      name: "{{ item.name }}"
      description: "{{ item.description }}"
      othername: "{{ item.othername }}"
    loop: "{{ networkdevicegroups }}"


...
