---
#
# ISE Internal User
#
- name: Create Internal User(s) Play
  hosts: ise_deployment
  vars:
    - staticGroupAssignment_default: true
    - staticGroupProfile_default: false
    - groupId_default: aa13bb40-8bff-11e6-996c-525400b48521

    - endpoints:

      - mac: 11:22:33:44:55:66
        name: Thomas-iPad
        description: iPad
        staticGroupAssignment: true
        groupId: aa13bb40-8bff-11e6-996c-525400b48521


      # - mac: 11:22:33:44:55:67
      #   name: Thomas-iPad
      #   description: iPad
      #   staticGroupAssignment: true
      #   groupId: aa13bb40-8bff-11e6-996c-525400b48521


  vars_files:
    - credentials.yaml
  gather_facts: no
  tasks:

  - name: Create Endpoints
    loop: "{{ endpoints }}"
    cisco.ise.endpoint:
      ise_hostname: "{{ inventory_hostname }}"
      ise_username: "{{ ise_username }}"
      ise_password: "{{ ise_password }}"
      ise_verify: "{{ ise_verify }}"
      state: present
      mac: "{{ item.mac }}"
      name: "{{ item.name }}"
      description: "{{ item.description | default() }}"

      # ▼▼▼ optional attributes ▼▼▼
      # staticGroupAssignment: "{{ item.staticGroupAssignment | default( staticGroupAssignment_default ) }}"
      # groupId: "{{ item.groupId | default( groupId_default )}}"

      # staticProfileAssignment: true
      # profileId: 0a9c6890-8c00-11e6-996c-525400b48521

      # customAttributes:
      #   customAttributes:
      #     Created: "{{ created | default(now()) }}"
      #     Expired: 


    register: results


  - name: Debug results
    ansible.builtin.debug:
      var: results


...