---
#
# Endpoint with Custom Attributes
#
- name: Create Internal User(s) Play
  hosts: ise_deployment
  vars_files:
    - credentials.yaml
  gather_facts: no
  tasks:


  - name: Create Endpoint
    cisco.ise.endpoint:
      ise_hostname: "{{ inventory_hostname }}"
      ise_username: "{{ ise_username }}"
      ise_password: "{{ ise_password }}"
      ise_verify: "{{ ise_verify }}"
      state: present

      mac: 11:22:33:44:55:66
      name: Thomas-iPad
      description: iPad

      # ▼▼▼ optional attributes ▼▼▼

      # ⟁ you must lookup and confirm the groupId for your EndpointGroup!
      # staticGroupAssignment: true
      # groupId: aa13bb40-8bff-11e6-996c-525400b48521

      # ⟁ you must lookup and confirm the profileId!
      # staticProfileAssignment: true
      # profileId: 0a9c6890-8c00-11e6-996c-525400b48521

      # 🛑 You MUST create these using the ISE GUI before you can use them!
      customAttributes:
        customAttributes:
          Created: "{{ now().timestamp() | int }}"
          # expires in 4 hours:
          Expired: "{{ ( now().timestamp() + (4 * 60 * 60) ) | int }}"

    register: results


  - name: Debug
    ansible.builtin.debug: var=results


...