---

# By default, Ansible gathers facts at the beginning of each play.
# If you do not need to gather facts (for example, if you know 
# everything about your systems centrally), you can turn off fact 
# gathering at the play level to improve scalability. Disabling 
# facts may particularly improve performance in push mode with 
# very large numbers of systems, or if you are using Ansible on 
# experimental platforms. 
# To disable fact gathering, use: 
#   gather_facts: no

- hosts: localhost
  # gather_facts: no
  tasks:

- hosts: whatever
  gather_facts: no

  - name: Show ansible_facts
    ansible.builtin.debug:
      msg: "{{ ansible_facts }}"

  - name: Show all_ipv4_addresses
    ansible.builtin.debug:
      msg: "{{ ansible_facts.all_ipv4_addresses }}"
