---
#
# Demonstrates :
# - Ansible fact gathering on localhost (control node)
# - ansible_facts variable output 
# - dictionary object notation
#
- hosts: localhost
  # gather_facts: no
  tasks:


  - name: Show ansible_facts
    ansible.builtin.debug:
      msg: "{{ ansible_facts }}"


  - name: Show all_ipv4_addresses
    ansible.builtin.debug:
      msg: "{{ ansible_facts.all_ipv4_addresses }}"
