---
#
# Demonstrates :
# - ansible.builtin.shell module on localhost (control node)
# - local variable registration and output
# - dictionary and list object notation
# - ansible.builtin.debug msg versus var output
#
- hosts: localhost
  # remote_user: root
  # become: yes
  gather_facts: no
  tasks:

    - name: Run shell command `ls` in current directory
      ansible.builtin.shell: /bin/ls
      register: files

    - name: Show result
      ansible.builtin.debug:
        var: files

    - name: List files
      ansible.builtin.debug:
        var: files.stdout_lines

    - name: First file
      ansible.builtin.debug:
        var: files.stdout_lines[0]

    - name: Last file
      ansible.builtin.debug:
        msg: "{{ files.stdout_lines[-1] }}"

...