---
#
# Demonstrates the use of:
# - ansible.builtin.uri module from localhost with a web page
# - ansible.builtin.debug multiple msg versus single var output
#

- name: GET cisco.com
  hosts: localhost
  gather_facts: no
  tasks:

  - name: Get web page
    ansible.builtin.uri:
      url: "https://cisco.com"
    register: page


  - name: Show web page attributes in message(s)
    ansible.builtin.debug: 
      msg :
      # - "{{ page.cache_control }}"
      # - "{{ page.cdchost }}"
      # - "{{ page.changed }}"
      # - "{{ page.connection }}"
      # - "{{ page.content }}"
      # - "{{ page.content_type }}"
      # - "{{ page.cookies }}"
      # - "{{ page.cookies_string }}"
      - "Date: {{ page.date }}"
      # - "{{ page.elapsed }}"
      # - "{{ page.etag }}"
      # - "{{ page.expires }}"
      # - "{{ page.failed }}"
      # - "{{ page.link }}"
      # - "{{ page.msg }}"
      # - "{{ page.pragma }}"
      # - "{{ page.redirected }}"
      # - "{{ page.server }}"
      - "Status: {{ page.status }}"
      # - "{{ page.strict_transport_security }}"
      # - "{{ page.transfer_encoding }}"
      - "URL: {{ page.url }}"
      # - "{{ page.vary }}"
      # - "{{ page.x_content_type_options }}"
      # - "{{ page.x_frame_options }}"
      # - "{{ page.x_test_debug }}"
      # - "{{ page.x_xss_protection }}"


  - name: Show web page attributes as variable
    ansible.builtin.debug: 
      var : page.status
      # 
      # Pick one from below. Mutually exclusive with the msg option.
      #
      # page.cache_control
      # page.cdchost
      # page.changed
      # page.connection
      # page.content
      # page.content_type
      # page.cookies
      # page.cookies_string
      # page.date
      # page.elapsed
      # page.etag
      # page.expires
      # page.failed
      # page.link
      # page.msg
      # page.pragma
      # page.redirected
      # page.server
      # page.status
      # page.strict_transport_security
      # page.transfer_encoding
      # page.url
      # page.vary
      # page.x_content_type_options
      # page.x_frame_options
      # page.x_test_debug
      # page.x_xss_protection

...