---
#
# This credentials file is not encrypted for educational and demonstration 
# purposes. It is highly recommended to encrypt this file with Ansible Vault 
# or other encryption mechanism to protect your secrets!
#
ise_hostname: ise.securitydemo.net
ise_username: admin
ise_password: "C1sco12345"
ise_verify: false

radius_secret: C1sco12345
tacacs_secret: C1sco12345
snmp_secret: C1sco12345

